### ISSUE TITLE
Parameters not added to request path as query in GET list requests

### ISSUE THREAD

**Issue by GregLMcDonald** [whitepaperclip/SquareUp#2]
The parameters of a GET list request need to be added as a query to the path as body of these methods must be empty. 
 For example, the `types` and `cursor` parameters are in the `params_spec` of `Catalog.list` but should be in the `path_params_spec` and added as a query to the path.  For example, to get just the Catalog ITEM objects, the endpoint is `/v2/catalog/list?types=ITEM`.

Single record GET requests in the library seem to handle these params correctly. For example the `customer_id` param is added to the path in `Customer.retrieve`.

**Comment by nkezhaya** [comment]
Closed by PR #1
